import Head from "next/head";
import Image from "next/image";
import { Col, Input, Row } from "antd";
import Wrapper from "./style";
import { Form, Button } from "../../../components";
import { ImageWadhbank } from "../../../assets";

const Index = () => {
  return (
    <Wrapper>
      <Head>
        <title>Wadhbank - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Col className="container_login">
        <Row className="component_login_row">
          <Col className="component_login_card">
            <Row className="component_login_card_row">
              <Col className="component_login_card_logo">
                <Image src={ImageWadhbank} alt="wadhbank logo" />
              </Col>
              <Col className="component_login_card_label">
                Login into your account to continue
              </Col>
              <Form
                layout="vertical"
                className="component_login_card_form login-form"
              >
                <Row className="component_login_card_label_form_row">
                  <Col
                    span={24}
                    className="component_login_card_label_form_email"
                  >
                    <Form.Item label="Email or username" name="name">
                      <Input placeholder="Enter your email or username" />
                    </Form.Item>
                  </Col>
                  <Col span={24}>
                    <Form.Item
                      label="Password"
                      name="password"
                      className="password-form"
                    >
                      <Input.Password placeholder="Enter your password" />
                    </Form.Item>
                  </Col>
                  <Col
                    span={24}
                    className="component_login_card_label_form_submit"
                  >
                    <Button block type="primary">
                      Login
                    </Button>
                  </Col>
                </Row>
              </Form>
            </Row>
          </Col>
          <Col className="component_login_footer">
            2021 Copyright WadhBank, LLC. All right reserved
          </Col>
        </Row>
      </Col>
    </Wrapper>
  );
};

export default Index;
