import { Col, Row, Menu } from "antd";
import Head from "next/head";
import Image from "next/image";
import {
  IconChevronDown,
  IconLogout,
  IconMale,
  ImageWadhbank,
} from "../../assets";
import Wrapper, { DropdownMenus, Header } from "./style";

const menu = (
  <Menu className="component_dropdown_menus">
    <Menu.Item key="0" className="component_dropdown_menus_item account">
      <Row gutter={[4, 4]}>
        <Col span={24} className="component_account">
          john.doe@gmail.com
        </Col>
        <Col span={24} className="component_account_role">
          Admin
        </Col>
      </Row>
    </Menu.Item>
    <Menu.Divider />
    <Menu.Item key="1" className="component_dropdown_menus_item links">
      <Row gutter={[4, 4]}>
        <Col span={24} className="component_link">
          <Row gutter={12} align="middle">
            <Col>
              <IconLogout />
            </Col>
            <Col>Logout</Col>
          </Row>
        </Col>
      </Row>
    </Menu.Item>
  </Menu>
);

export default function Index() {
  return (
    <Wrapper>
      <Head>
        <title>Wadhbank - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <Row className="container_header">
          <Col className="component_logo">
            <Image src={ImageWadhbank} alt="wadhbank" objectFit="cover" />
          </Col>
          <Col className="component_nav">Waiting List</Col>
          <Col className="component_menus">
            <DropdownMenus
              overlay={menu}
              overlayClassName="component_menus_overlay"
              getPopupContainer={(trigger) => {
                return trigger;
              }}
              placement="bottomRight"
            >
              <Row gutter={8} align="middle">
                <Col>
                  <Image src={IconMale} height={36} width={36} alt="avatar" />
                </Col>
                <Col>
                  <IconChevronDown />
                </Col>
              </Row>
            </DropdownMenus>
          </Col>
        </Row>
      </Header>
      <p>This is the Dashboard page.</p>
    </Wrapper>
  );
}
