import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useSession } from "next-auth/client";
import { Col, Row, Menu, Spin } from "antd";
import {
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconFile,
  IconLogout,
  IconMale,
  ImageWadhbank,
} from "../../assets";
import Wrapper, { DropdownMenus, Header, PaginationCustom } from "./style";
import { Table, Button } from "../../components";
import { waitingList } from "./dummy";
import columns from "./column.table";
import URL from "../../configs/baseUrl";

const menu = (
  <Menu className="component_dropdown_menus">
    <Menu.Item key="0" className="component_dropdown_menus_item account">
      <Row gutter={[4, 4]}>
        <Col span={24} className="component_account">
          john.doe@gmail.com
        </Col>
        <Col span={24} className="component_account_role">
          Admin
        </Col>
      </Row>
    </Menu.Item>
    <Menu.Divider />
    <Menu.Item key="1" className="component_dropdown_menus_item links">
      <Row gutter={[4, 4]}>
        <Col span={24} className="component_link">
          <Row gutter={12} align="middle">
            <Col>
              <IconLogout />
            </Col>
            <Col>Logout</Col>
          </Row>
        </Col>
      </Row>
    </Menu.Item>
  </Menu>
);

const pageSize = 25;
export default function Index() {
  const router = useRouter();

  const [session, loading] = useSession();
  const [currentPage, setCurrentPage] = useState(0);
  const [isLoading, setIsLoading] = useState(true);
  const [userList, setUserList] = useState([]);

  useEffect(() => {
    setUserList(waitingList);
    setIsLoading(false);
  }, []);

  const isSessionValid = (session) => {
    if (
      typeof session !== typeof undefined &&
      session !== null &&
      typeof session.user !== typeof undefined
    ) {
      return true;
    } else {
      return false;
    }
  };

  if (loading) {
    return <Spin />;
  } else {
    if (!isSessionValid(session)) {
      return (
        <div className="wrapper">
          <p>You are not logged in</p>
        </div>
      );
    }
  }

  const onGetCurrentShowing = () => {
    const indexOfLast = (currentPage + 1) * pageSize;
    const indexOfFirst = indexOfLast - pageSize;
    const currentData = userList?.slice(indexOfFirst, indexOfLast);
    const startIndex = currentPage * pageSize + 1;
    const endIndex = currentPage * pageSize + currentData?.length;
    return `Showing ${startIndex}-${endIndex} data of ${userList?.length} data`;
  };

  return (
    <Wrapper>
      <Head>
        <title>Wadhbank - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <Row className="container_header">
          <Col
            className="component_logo"
            onClick={() => {
              router.push(URL.LANDING);
            }}
          >
            <Image src={ImageWadhbank} alt="wadhbank" objectFit="cover" />
          </Col>
          <Col className="component_nav">Waiting List</Col>
          <Col className="component_menus">
            <DropdownMenus
              trigger={["click"]}
              overlay={menu}
              overlayClassName="component_menus_overlay"
              getPopupContainer={(trigger) => {
                return trigger;
              }}
              placement="bottomRight"
            >
              <Row gutter={8} align="middle">
                <Col>
                  <Image src={IconMale} height={36} width={36} alt="avatar" />
                </Col>
                <Col>
                  <IconChevronDown />
                </Col>
              </Row>
            </DropdownMenus>
          </Col>
        </Row>
      </Header>
      <Col span={24} className="container_waiting_list">
        <Row>
          <Col span={24} className="component_waiting_list_header">
            <Row justify="space-between" align="middle">
              <Col className="component_waiting_list_header_title">
                Waiting List
              </Col>
              <Col className="component_waiting_list_header_export">
                <Button type="default">
                  <Row align="middle" gutter={16}>
                    <Col className="component_waiting_list_header_export_icon">
                      <IconFile />
                    </Col>
                    <Col className="component_waiting_list_header_export_label">
                      Export to excel
                    </Col>
                  </Row>
                </Button>
              </Col>
            </Row>
          </Col>
          <Col span={24} className="component_waiting_list_table">
            <Col span={24} className="component_waiting_list_table_header">
              <Row
                justify="space-between"
                align="middle"
                className="component_waiting_list_table_header_row"
              >
                <Col className="component_waiting_list_table_header_total">
                  Total user on waiting list:&nbsp;
                  <span className="component_total_bold">{`${userList?.length} people`}</span>
                </Col>
                {userList?.length !== 0 && (
                  <Col className="component_waiting_list_table_header_pagination">
                    <Row gutter={16} align="middle" wrap={false}>
                      <Col className="component_pagination_showing">
                        {onGetCurrentShowing()}
                      </Col>
                      <Col className="component_pagination_handler">
                        <PaginationCustom
                          current={currentPage + 1}
                          total={userList.length}
                          pageSize={pageSize}
                          onChange={(page) => {
                            setCurrentPage(page - 1);
                          }}
                          itemRender={(_, type, originElement) => {
                            if (type === "prev") {
                              return <IconChevronLeft />;
                            }
                            if (type === "next") {
                              return <IconChevronRight />;
                            }
                            return originElement;
                          }}
                        />
                      </Col>
                    </Row>
                  </Col>
                )}
              </Row>
            </Col>
            <Col span={24} className="component_waiting_list_table_content">
              <Table
                dataSource={userList}
                columns={columns({ currentPage, pageSize })}
                rowKey="id"
                loading={isLoading}
                pagination={{
                  pageSize,
                  style: { display: "none" },
                  current: currentPage + 1,
                }}
              />
            </Col>
          </Col>
        </Row>
      </Col>
    </Wrapper>
  );
}
