import Head from "next/head";
import { Button, Collapse, Header, Typography } from "../../components";

export default function Components() {
  return (
    <>
      <Head>
        <title>Components</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="h-full bg-black-40 px-40 py-20 flex flex-col gap-16">
        <div className="flex flex-col gap-2">
          <Typography size="heading-1" weight="bold">
            Font Heading H1
          </Typography>
          <Typography size="heading-5" weight="bold">
            Font Heading H5
          </Typography>
          <Typography size="heading-6" weight="bold">
            Font Heading H6
          </Typography>
          <Typography size="large" weight="bold">
            Font Large Bold
          </Typography>
          <Typography size="large" weight="medium">
            Font Large Medium
          </Typography>
          <Typography size="large" weight="regular">
            Font Large Regular
          </Typography>
          <Typography size="normal" weight="bold">
            Font Normal Bold
          </Typography>
          <Typography size="normal" weight="medium">
            Font Normal Medium
          </Typography>
          <Typography size="normal" weight="regular">
            Font Normal Regular
          </Typography>
          <Typography size="small" weight="bold">
            Font Small Bold
          </Typography>
          <Typography size="small" weight="medium">
            Font Small Medium
          </Typography>
          <Typography size="small" weight="regular">
            Font Small Regular
          </Typography>
          <Typography size="extra-small" weight="bold">
            Font Extra Small Bold
          </Typography>
          <Typography size="extra-small" weight="medium">
            Font Extra Small Medium
          </Typography>
          <Typography size="extra-small" weight="regular">
            Font Extra Small Regular
          </Typography>
        </div>
        <div className="flex flex-wrap flex-row items-center gap-2">
          <Button theme="primary" size="medium">
            Primary Button
          </Button>
          <Button theme="secondary" size="medium">
            Secondary Button
          </Button>
          <Button theme="default" size="medium">
            Default Button
          </Button>
          <Button theme="primary" size="small">
            Primary Button
          </Button>
          <Button theme="secondary" size="small">
            Secondary Button
          </Button>
          <Button theme="default" size="small">
            Default Button
          </Button>
        </div>
        <div className="">
          <Collapse
            title="What is WadhBank?"
            content="Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est."
          />
        </div>
      </div>
    </>
  );
}
