import Head from "next/head";
import { Button, Collapse, Header } from "../../components";

export default function Components() {
  return (
    <>
      <Head>
        <title>Components</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="h-full py-36 bg-black-40 px-40 flex flex-col gap-16">
        <div className="flex flex-col gap-2">
          <div className="prose-heading-1">Font Heading H1</div>
          <div className="prose-heading-5">Font Heading H5</div>
          <div className="prose-heading-6">Font Heading H6</div>
          <div className="prose-large-bold">Font Large Bold</div>
          <div className="prose-large-medium">Font Large Medium</div>
          <div className="prose-large-regular">Font Large Regular</div>
          <div className="prose-normal-bold">Font Normal Bold</div>
          <div className="prose-normal-medium">Font Normal Medium</div>
          <div className="prose-normal-regular">Font Normal Regular</div>
          <div className="prose-small-bold">Font Small Bold</div>
          <div className="prose-small-medium">Font Small Medium</div>
          <div className="prose-small-regular">Font Small Regular</div>
          <div className="prose-extra-small-bold">Font Extra Small Bold</div>
          <div className="prose-extra-small-medium">
            Font Extra Small Medium
          </div>
          <div className="prose-extra-small-regular">
            Font Extra Small Regular
          </div>
        </div>
        <div className="flex flex-wrap flex-row items-center gap-2">
          <Button theme="primary" size="medium">
            Primary Button
          </Button>
          <Button theme="secondary" size="medium">
            Secondary Button
          </Button>
          <Button theme="default" size="medium">
            Default Button
          </Button>
          <Button theme="primary" size="small">
            Primary Button
          </Button>
          <Button theme="secondary" size="small">
            Secondary Button
          </Button>
          <Button theme="default" size="small">
            Default Button
          </Button>
        </div>
        <div className="">
          <Collapse
            title="What is WadhBank?"
            content="Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est."
          />
        </div>
      </div>
    </>
  );
}
